

path: C:\Users\adeda\OneDrive\Desktop\car  # dataset root directory
train: images/  # train images (relative to 'path')
val: images/  # val images (relative to 'path')

# Classes
nc: 1 # number of classes
names: ['car']  # list of class names